--- Table"MONI_T"
CREATE TABLE MONI_T (
 KYOKUSHA_COD integer NOT NULL
, KYOKUSHA_NM character varying(40) NOT NULL
, NEKND_NM character varying(20) NOT NULL
, DEV_NM character varying(80) NOT NULL
, ALM_STS_CD character varying(4)
, MONI_CASE_NM character varying(30)
, HPNTIME character varying(19)
, TFM_HPNTIME_UNIX integer
, TFM_LOGKND_NO integer
, TFM_BEF_HPNTIME_UNIX integer
, TFM_BEF_LOGKND_NO integer
, MONI_CASE_MIN_UNIX integer
, MASK_START_DT_UNIX integer
, MASK_END_DT_UNIX integer
, ALT_OUT_FLG character varying(5)
);
COMMENT ON COLUMN MONI_T.KYOKUSHA_COD IS '局舎コード';
COMMENT ON COLUMN MONI_T.KYOKUSHA_NM IS '局舎名称';
COMMENT ON COLUMN MONI_T.NEKND_NM IS '装置種別名称';
COMMENT ON COLUMN MONI_T.DEV_NM IS '装置名称';
COMMENT ON COLUMN MONI_T.ALM_STS_CD IS '発生状況';
COMMENT ON COLUMN MONI_T.MONI_CASE_NM IS '監視条件名称';
COMMENT ON COLUMN MONI_T.HPNTIME IS '発生時刻';
COMMENT ON COLUMN MONI_T.TFM_HPNTIME_UNIX IS 'TFM発生時刻';
COMMENT ON COLUMN MONI_T.TFM_LOGKND_NO IS 'TFMロギング種別';
COMMENT ON COLUMN MONI_T.TFM_BEF_HPNTIME_UNIX IS '前TFM発生時刻';
COMMENT ON COLUMN MONI_T.TFM_BEF_LOGKND_NO IS '前TFMロギング種別';
COMMENT ON COLUMN MONI_T.MONI_CASE_MIN_UNIX IS '間隔（分）';
COMMENT ON COLUMN MONI_T.MASK_START_DT_UNIX IS 'マスク開始日時';
COMMENT ON COLUMN MONI_T.MASK_END_DT_UNIX IS 'マスク終了日時';
COMMENT ON COLUMN MONI_T.ALT_OUT_FLG IS '警報出力要否';
COMMENT ON TABLE MONI_T IS '監視情報';

--- Table"MONI_CASE_T"
CREATE TABLE MONI_CASE_T (
 MONI_CASE_SEQ character varying(10) NOT NULL
, KYOKUSHA_COD integer NOT NULL
, DEV_NM character varying(80) NOT NULL
, MONI_CASE_CD character varying(4) NOT NULL
, UPD_USER character varying(50) NOT NULL
, UPD_DT character varying(30) NOT NULL
);
COMMENT ON COLUMN MONI_CASE_T.MONI_CASE_SEQ IS '監視条件通番';
COMMENT ON COLUMN MONI_CASE_T.KYOKUSHA_COD IS '局所コード';
COMMENT ON COLUMN MONI_CASE_T.DEV_NM IS '装置名称';
COMMENT ON COLUMN MONI_CASE_T.MONI_CASE_CD IS '監視条件';
COMMENT ON COLUMN MONI_CASE_T.UPD_USER IS '更新者';
COMMENT ON COLUMN MONI_CASE_T.UPD_DT IS '更新日時';
ALTER TABLE ONLY MONI_CASE_T ADD CONSTRAINT m_MONI_CASE_T_pkey PRIMARY KEY (MONI_CASE_SEQ);
COMMENT ON TABLE MONI_CASE_T IS '監視条件情報';

--- Table"MASK_T"
CREATE TABLE MASK_T (
 MASK_SEQ character varying(10) NOT NULL
, KYOKUSHA_COD integer NOT NULL
, DEV_NM character varying(80) NOT NULL
, START_DT_YMD character varying(10) NOT NULL
, END_DT_YMD character varying(10)
, START_DT_HM character varying(5) NOT NULL
, END_DT_HM character varying(5)
, START_DT_UNIX integer NOT NULL
, END_DT_UNIX integer NOT NULL
, INS_USER character varying(50) NOT NULL
, INS_DT character varying(30) NOT NULL
, INS_DT_UNIX integer NOT NULL
, DEL_USER character varying(50)
, DEL_DT character varying(30)
, DEL_DT_UNIX integer
);
COMMENT ON COLUMN MASK_T.MASK_SEQ IS 'マスク情報通番';
COMMENT ON COLUMN MASK_T.KYOKUSHA_COD IS '局舎コード';
COMMENT ON COLUMN MASK_T.DEV_NM IS '装置名称';
COMMENT ON COLUMN MASK_T.START_DT_YMD IS '開始年月日';
COMMENT ON COLUMN MASK_T.END_DT_YMD IS '終了年月日';
COMMENT ON COLUMN MASK_T.START_DT_HM IS '開始時刻';
COMMENT ON COLUMN MASK_T.END_DT_HM IS '終了時刻';
COMMENT ON COLUMN MASK_T.START_DT_UNIX IS '開始日時（UNIX積算秒）';
COMMENT ON COLUMN MASK_T.END_DT_UNIX IS '終了日時（UNIX積算秒）';
COMMENT ON COLUMN MASK_T.INS_USER IS '登録者';
COMMENT ON COLUMN MASK_T.INS_DT IS '登録日時';
COMMENT ON COLUMN MASK_T.INS_DT_UNIX IS '登録日時（UNIX積算秒）';
COMMENT ON COLUMN MASK_T.DEL_USER IS '削除者';
COMMENT ON COLUMN MASK_T.DEL_DT IS '削除日時';
COMMENT ON COLUMN MASK_T.DEL_DT_UNIX IS '削除日時（UNIX積算秒）';
ALTER TABLE ONLY MASK_T ADD CONSTRAINT m_MASK_T_pkey PRIMARY KEY (MASK_SEQ);
COMMENT ON TABLE MASK_T IS 'マスク情報';

--- Table"MONI_CASE_MASTER_T"
CREATE TABLE MONI_CASE_MASTER_T (
 MONI_CASE_CD character varying(4) NOT NULL
, MONI_CASE_NM character varying(30) NOT NULL
, MONI_CASE_MIN integer
, MONI_CASE_MIN_UNIX integer
, DISP_ORDER integer NOT NULL
);
COMMENT ON COLUMN MONI_CASE_MASTER_T.MONI_CASE_CD IS '監視条件';
COMMENT ON COLUMN MONI_CASE_MASTER_T.MONI_CASE_NM IS '監視条件名称';
COMMENT ON COLUMN MONI_CASE_MASTER_T.MONI_CASE_MIN IS '間隔（分）';
COMMENT ON COLUMN MONI_CASE_MASTER_T.MONI_CASE_MIN_UNIX IS '間隔（分）_UNIX';
COMMENT ON COLUMN MONI_CASE_MASTER_T.DISP_ORDER IS '表示順';
ALTER TABLE ONLY MONI_CASE_MASTER_T ADD CONSTRAINT m_MONI_CASE_MASTER_T_pkey PRIMARY KEY (MONI_CASE_CD);
COMMENT ON TABLE MONI_CASE_MASTER_T IS '監視条件マスタ';

--- Table"VLANID_MANAGE_T"
CREATE TABLE VLANID_MANAGE_T (
 SIDE_CD char NOT NULL
, AREA_CD char NOT NULL
, VLAN_ID char NOT NULL
, CLASS_CD char
, VLAN_SVC_NM_SEQ char
, MEMO character varying(64)
, ISSUE_DT char
, DUE_DT char
, UPD_DT char NOT NULL
);
COMMENT ON COLUMN VLANID_MANAGE_T.SIDE_CD IS '面コード';
COMMENT ON COLUMN VLANID_MANAGE_T.AREA_CD IS 'エリアコード';
COMMENT ON COLUMN VLANID_MANAGE_T.VLAN_ID IS 'VLAN-ID';
COMMENT ON COLUMN VLANID_MANAGE_T.CLASS_CD IS '分類コード';
COMMENT ON COLUMN VLANID_MANAGE_T.VLAN_SVC_NM_SEQ IS 'VLANサービス名管理通番';
COMMENT ON COLUMN VLANID_MANAGE_T.MEMO IS 'メモ';
COMMENT ON COLUMN VLANID_MANAGE_T.ISSUE_DT IS '割当日時';
COMMENT ON COLUMN VLANID_MANAGE_T.DUE_DT IS '返却日時';
COMMENT ON COLUMN VLANID_MANAGE_T.UPD_DT IS '更新日時';
ALTER TABLE ONLY VLANID_MANAGE_T ADD CONSTRAINT m_VLANID_MANAGE_T_pkey PRIMARY KEY (SIDE_CD,AREA_CD,VLAN_ID);
COMMENT ON TABLE VLANID_MANAGE_T IS 'VLANID管理情報';

--- Table"VLAN_SVC_NM_MASTER_T"
CREATE TABLE VLAN_SVC_NM_MASTER_T (
 VLAN_SVC_NM_SEQ char NOT NULL
, VLAN_SVC_NM character varying(70) NOT NULL
, USE_STS char NOT NULL
, DEL_FLG char NOT NULL
, UPD_DT char NOT NULL
);
COMMENT ON COLUMN VLAN_SVC_NM_MASTER_T.VLAN_SVC_NM_SEQ IS 'VLANサービス名管理通番';
COMMENT ON COLUMN VLAN_SVC_NM_MASTER_T.VLAN_SVC_NM IS 'VLANサービス名';
COMMENT ON COLUMN VLAN_SVC_NM_MASTER_T.USE_STS IS '使用状態';
COMMENT ON COLUMN VLAN_SVC_NM_MASTER_T.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN VLAN_SVC_NM_MASTER_T.UPD_DT IS '更新日時';
ALTER TABLE ONLY VLAN_SVC_NM_MASTER_T ADD CONSTRAINT m_VLAN_SVC_NM_MASTER_T_pkey PRIMARY KEY (VLAN_SVC_NM_SEQ);
COMMENT ON TABLE VLAN_SVC_NM_MASTER_T IS 'VLANサービス名マスタ';

--- Table"VLAN_SVC_NM_ISSUE_DUE_T"
CREATE TABLE VLAN_SVC_NM_ISSUE_DUE_T (
 VLAN_SVC_NM_SEQ char NOT NULL
, SIDE_CD char NOT NULL
, AREA_CD char NOT NULL
, USE_STS char NOT NULL
, UPD_DT char NOT NULL
);
COMMENT ON COLUMN VLAN_SVC_NM_ISSUE_DUE_T.VLAN_SVC_NM_SEQ IS 'VLANサービス名管理通番';
COMMENT ON COLUMN VLAN_SVC_NM_ISSUE_DUE_T.SIDE_CD IS '面コード';
COMMENT ON COLUMN VLAN_SVC_NM_ISSUE_DUE_T.AREA_CD IS 'エリアコード';
COMMENT ON COLUMN VLAN_SVC_NM_ISSUE_DUE_T.USE_STS IS '使用状態';
COMMENT ON COLUMN VLAN_SVC_NM_ISSUE_DUE_T.UPD_DT IS '更新日時';
ALTER TABLE ONLY VLAN_SVC_NM_ISSUE_DUE_T ADD CONSTRAINT m_VLAN_SVC_NM_ISSUE_DUE_T_pkey PRIMARY KEY (VLAN_SVC_NM_SEQ,SIDE_CD,AREA_CD);
COMMENT ON TABLE VLAN_SVC_NM_ISSUE_DUE_T IS 'VLANサービス名割当返却情報';

--- Table"CLASS_RANGE_MANAGE_T"
CREATE TABLE CLASS_RANGE_MANAGE_T (
 SIDE_CD char NOT NULL
, AREA_CD char NOT NULL
, VLAN_ID char NOT NULL
, CLASS_CD char NOT NULL
, UPD_DT char NOT NULL
);
COMMENT ON COLUMN CLASS_RANGE_MANAGE_T.SIDE_CD IS '面コード';
COMMENT ON COLUMN CLASS_RANGE_MANAGE_T.AREA_CD IS 'エリアコード';
COMMENT ON COLUMN CLASS_RANGE_MANAGE_T.VLAN_ID IS 'VLAN-ID';
COMMENT ON COLUMN CLASS_RANGE_MANAGE_T.CLASS_CD IS '分類コード';
COMMENT ON COLUMN CLASS_RANGE_MANAGE_T.UPD_DT IS '更新日時';
ALTER TABLE ONLY CLASS_RANGE_MANAGE_T ADD CONSTRAINT m_CLASS_RANGE_MANAGE_T_pkey PRIMARY KEY (SIDE_CD,AREA_CD,VLAN_ID,CLASS_CD);
COMMENT ON TABLE CLASS_RANGE_MANAGE_T IS '分類範囲管理情報';

--- Table"CD_MASTER_T"
CREATE TABLE CD_MASTER_T (
 ACCESS_KEY character varying(10) NOT NULL
, CD character varying(10) NOT NULL
, VALUE_1 character varying(20)
, VALUE_2 character varying(20)
, VALUE_3 character varying(20)
, VALUE_4 character varying(20)
, VALUE_5 character varying(20)
, DISP_ORDER integer
);
COMMENT ON COLUMN CD_MASTER_T.ACCESS_KEY IS 'アクセスキー';
COMMENT ON COLUMN CD_MASTER_T.CD IS 'コード';
COMMENT ON COLUMN CD_MASTER_T.VALUE_1 IS '値1';
COMMENT ON COLUMN CD_MASTER_T.VALUE_2 IS '値2';
COMMENT ON COLUMN CD_MASTER_T.VALUE_3 IS '値3';
COMMENT ON COLUMN CD_MASTER_T.VALUE_4 IS '値4';
COMMENT ON COLUMN CD_MASTER_T.VALUE_5 IS '値5';
COMMENT ON COLUMN CD_MASTER_T.DISP_ORDER IS '表示順';
ALTER TABLE ONLY CD_MASTER_T ADD CONSTRAINT m_CD_MASTER_T_pkey PRIMARY KEY (ACCESS_KEY,CD);
COMMENT ON TABLE CD_MASTER_T IS 'コードマスタ';

--- Table"SYSTEM_PRM_T"
CREATE TABLE SYSTEM_PRM_T (
 ACCESS_KEY character varying(10) NOT NULL
, VALUE_1 character varying(100)
, VALUE_2 character varying(100)
, VALUE_3 character varying(100)
, VALUE_4 character varying(100)
, VALUE_5 character varying(100)
);
COMMENT ON COLUMN SYSTEM_PRM_T.ACCESS_KEY IS 'アクセスキー';
COMMENT ON COLUMN SYSTEM_PRM_T.VALUE_1 IS '値1';
COMMENT ON COLUMN SYSTEM_PRM_T.VALUE_2 IS '値2';
COMMENT ON COLUMN SYSTEM_PRM_T.VALUE_3 IS '値3';
COMMENT ON COLUMN SYSTEM_PRM_T.VALUE_4 IS '値4';
COMMENT ON COLUMN SYSTEM_PRM_T.VALUE_5 IS '値5';
COMMENT ON TABLE SYSTEM_PRM_T IS 'システム定義';


